pipeline:
  agent:
    any: true

  stages:

    - stage: "Show Workspace"
      steps:
        - "bat dir"

    - stage: "Copy Files"
      steps:
        - "bat copy iis_structure.csv C:\\Batchfile\\iis_structure.csv /Y"
        - "bat copy create_sites.ps1 C:\\Batchfile\\create_sites.ps1 /Y"

    - stage: "Run IIS Script"
      steps:
        - "bat powershell -ExecutionPolicy Bypass -File C:\\Batchfile\\create_sites.ps1"
