pipeline:
  agent:
    any: true

  stages:

    - stage: "Checkout"
      steps:
        - "checkout scm"

    - stage: "Check Files"
      steps:
        - "bat \"dir\""

    - stage: "Create Folder"
      steps:
        - "bat \"if not exist C:\\\\Jenkinsyml mkdir C:\\\\Jenkinsyml\""

    - stage: "Copy Files"
      steps:
        - "bat \"copy create_sites.ps1 C:\\\\Jenkinsyml\\\\create_sites.ps1 /Y\""
        - "bat \"copy iis_structure.csv C:\\\\Jenkinsyml\\\\iis_structure.csv /Y\""

    - stage: "Run IIS Script"
      steps:
        - "powershell \"C:\\\\Jenkinsyml\\\\create_sites.ps1\""
